name = "RandomQuadMesh"
uuid = "1033c436-49f1-455f-b2c2-3821fef5dd59"
authors = ["Arjun <arjun.narayanan91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
